[package]
name = "funpar-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
mnist = "0.6.0"
ndarray = "0.15.6"
flate2 = "1"
rust-mnist = "0.2"
rayon = "1.8"